# Don't edit the `bin` list manually! It is updated by `rustlings dev update`
bin = [
  { name = "01_move", path = "exercises/ownership/01_move.rs" },
  { name = "01_move_sol", path = "solutions/ownership/01_move.rs" },
  { name = "02_borrow", path = "exercises/ownership/02_borrow.rs" },
  { name = "02_borrow_sol", path = "solutions/ownership/02_borrow.rs" },
  { name = "03_mut_borrow", path = "exercises/ownership/03_mut_borrow.rs" },
  { name = "03_mut_borrow_sol", path = "solutions/ownership/03_mut_borrow.rs" },
  { name = "04_result", path = "exercises/errors/04_result.rs" },
  { name = "04_result_sol", path = "solutions/errors/04_result.rs" },
  { name = "05_repository", path = "exercises/traits/05_repository.rs" },
  { name = "05_repository_sol", path = "solutions/traits/05_repository.rs" },
  { name = "06_summary", path = "exercises/iterators/06_summary.rs" },
  { name = "06_summary_sol", path = "solutions/iterators/06_summary.rs" },
  { name = "07_lifetimes", path = "exercises/lifetimes/07_lifetimes.rs" },
  { name = "07_lifetimes_sol", path = "solutions/lifetimes/07_lifetimes.rs" },
  { name = "08_borrowed_struct", path = "exercises/lifetimes/08_borrowed_struct.rs" },
  { name = "08_borrowed_struct_sol", path = "solutions/lifetimes/08_borrowed_struct.rs" },
  { name = "09_borrowed_slice", path = "exercises/lifetimes/09_borrowed_slice.rs" },
  { name = "09_borrowed_slice_sol", path = "solutions/lifetimes/09_borrowed_slice.rs" },
  { name = "10_collections", path = "exercises/collections/10_collections.rs" },
  { name = "10_collections_sol", path = "solutions/collections/10_collections.rs" },
  { name = "11_modules", path = "exercises/modules/11_modules.rs" },
  { name = "11_modules_sol", path = "solutions/modules/11_modules.rs" },
  { name = "12_threads", path = "exercises/concurrency/12_threads.rs" },
  { name = "12_threads_sol", path = "solutions/concurrency/12_threads.rs" },
  { name = "13_future", path = "exercises/async/13_future.rs" },
  { name = "13_future_sol", path = "solutions/async/13_future.rs" },
  { name = "14_send_sync", path = "exercises/concurrency/14_send_sync.rs" },
  { name = "14_send_sync_sol", path = "solutions/concurrency/14_send_sync.rs" },
  { name = "15_retry_policy", path = "exercises/async/15_retry_policy.rs" },
  { name = "15_retry_policy_sol", path = "solutions/async/15_retry_policy.rs" },
  { name = "16_web_state", path = "exercises/web/16_web_state.rs" },
  { name = "16_web_state_sol", path = "solutions/web/16_web_state.rs" },
  { name = "17_storage_mapping", path = "exercises/storage/17_storage_mapping.rs" },
  { name = "17_storage_mapping_sol", path = "solutions/storage/17_storage_mapping.rs" },
]

[package]
name = "exercises"
edition = "2024"
# Don't publish the exercises on crates.io!
publish = false

[dependencies]
